apiVersion: v1
data:
  RPS_USER: '${parameters.user}'
kind: ConfigMap
metadata:
  name: rps-config
  namespace: '${execution.application}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rps
  namespace: '${execution.application}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rps
  template:
    metadata:
      labels:
        app: rps
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: rps-config
          image: 'away168/rps:v0.1.1'
          name: rps
          ports:
            - containerPort: 80
